


languageCode = "en-us"
title = "PraxisLIVE Unofficial Guide"
theme = "hugo-theme-hello-friend-ng"
publishDir = "public"

[module]

  [[module.mounts]]
    source = "content"
    target = "content"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "by Giacomo Sabatini"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[taxonomies]
    tag      = "tags"
    category = "categories"
    series   = "series"
    author   = "authors"

[languages]
  [languages.en]
    title = "PraxisLIVE Unofficial Guide"
    subtitle = "by Giacomo Sabatini"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"


    [languages.en.params.logo]
      logoText = "PraxisLIVE Guide"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [menu]
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

  [[menu.main]]
  identifier = "about"
  name       = "About"
  url        = "/about/about/"

  [[menu.main]]
  identifier = "tutorial"
  name       = "Tutorial"
  url        = "/tutorials/"
